name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create custom build script
      run: |
        cat <<EOT > build-with-polyfill.js
        // Script para proporcionar un polyfill para crypto
        const { execSync } = require('child_process');
        
        // Polyfill para crypto.getRandomValues
        global.crypto = {
          getRandomValues: function(array) {
            for (let i = 0; i < array.length; i++) {
              array[i] = Math.floor(Math.random() * 256);
            }
            return array;
          }
        };
        
        // Ejecutar Vite build
        try {
          console.log('Running vite build with polyfill...');
          execSync('npx vite build', { stdio: 'inherit' });
          console.log('Build successful!');
          console.log('Creating .nojekyll file...');
          require('fs').writeFileSync('dist/.nojekyll', '');
        } catch (error) {
          console.error('Build failed:', error);
          process.exit(1);
        }
        EOT
        
        chmod +x build-with-polyfill.js
    
    - name: Build with polyfill
      run: node build-with-polyfill.cjs
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist 