name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint (Non-blocking)
      run: |
        npm run lint || echo "Lint issues found, but continuing build..."
    
    - name: Test
      run: npm test || echo "No tests specified" && exit 0
    
    - name: Build
      run: npm run build
    
    # Agregar pasos adicionales para despliegue si es necesario 